name: Publish Docker image

on:
  push:
    branches: [master, release/*, paprika]
    paths: [src/Nethermind/**]

  workflow_dispatch:
    inputs:
      image-name:
        description: Image name
        required: true
        default: nethermind
      tag:
        description: Image tag
        required: true
      dockerfile:
        description: Dockerfile
        required: true
        default: Dockerfile
      build-config:
        description: Build configuration
        required: true
        default: release
        type: choice
        options: [release, debug]

jobs:
  publish-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to ghcr.io
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image to ghcr.io
        run: |
          branch=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
          tag=$(echo "${{ github.event.inputs.tag || '$branch' }}" | sed 's/\//-/g') # replace '/' with '-'
          image_name=nethermindeth/${{ github.event.inputs.image-name || 'nethermind' }}
          build_timestamp=$(date '+%s')
          
          echo "Building image with tag $tag"

          docker buildx build --platform=linux/amd64,linux/arm64 \
            -f ${{ github.event.inputs.dockerfile || 'Dockerfile' }} \
            -t "$image_name:$tag" \
            ${{ endsWith(github.ref, '/master') && github.event_name == 'push' && '-t $image_name:master-${GITHUB_SHA:0:7}' || '' }} \
            --build-arg BUILD_CONFIG=${{ github.event.inputs.build-config || 'release' }} \
            --build-arg BUILD_TIMESTAMP=$build_timestamp \
            --build-arg CI=$CI \
            --build-arg COMMIT_HASH=$GITHUB_SHA \
            . --push
